# Generated by Django 5.2.7 on 2025-12-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_alter_answer_author_alter_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='value',
            field=models.SmallIntegerField(default=1, verbose_name='Значение'),
        ),
    ]
